sudo: false
git:
  depth: 1
language: node_js
node_js: stable
after_script:
  - npm run-script coverage
  - npm install istanbul-coveralls
  - node node_modules/.bin/istanbul-coveralls
notifications:
  email: false
