init:
  - git config --global core.autocrlf input

version: '{build}'

environment:
  matrix:
    - nodejs_version: '0.10'
    - nodejs_version: '0.11'

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install --global npm bower
  - npm install --production
  - npm install each-exec require-bower-files script-equal tape
  - bower install

build: off

test_script:
  - ps: 'npm run-script test-only #PowerShell'
  - cmd: npm run-script test-only

cache:
  - bower_components
  - node_modules
  - 'C:\Users\appveyor\AppData\Roaming\npm\node_modules'
